name: Full Tests (with environment variables)

on:
  workflow_dispatch:  # Только ручной запуск

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run full tests
      env:
        PYTHONPATH: .
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        ASSISTANTS_CHAT_ID: ${{ secrets.ASSISTANTS_CHAT_ID }}
        FINANCE_CHAT_ID: ${{ secrets.FINANCE_CHAT_ID }}
        YANDEX_SPEECHKIT_API_KEY: ${{ secrets.YANDEX_SPEECHKIT_API_KEY }}
        YANDEX_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
        YANDEX_GPT_API_KEY: ${{ secrets.YANDEX_GPT_API_KEY }}
        YANDEX_GPT_FOLDER_ID: ${{ secrets.YANDEX_GPT_FOLDER_ID }}
      run: |
        python -m pytest tests/ -v --tb=short 